framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

                retry_strategy:
                    multiplier: 1

        routing:
            'App\Timer\Message\TimerMessage': async
