services:
  api_app:
    build:
      context: .
      dockerfile: docker/api/app/Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  api_nginx:
    build:
      context: .
      dockerfile: docker/api/nginx/Dockerfile
    depends_on:
      - api_app
    ports:
      - 80:80

  redis:
      image: redis
      volumes:
        - redis-data:/data

volumes:
  redis-data:
