version: "3.9"

services:
  api_app:
    build:
      context: .
      dockerfile: docker/prod/api/app/Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
    volumes:
      - public_files:/app/public
    depends_on:
      - redis

  api_nginx:
    build:
      context: .
      dockerfile: docker/prod/api/nginx/Dockerfile
    depends_on:
      - api_app
    volumes:
      - public_files:/app/public
    ports:
      - "80:80"

  worker_app:
    build:
      context: .
      dockerfile: docker/prod/worker/app/Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
    depends_on:
      - redis

  redis:
    image: redis:6.2.6
    volumes:
      - redis-data:/data

volumes:
  public_files:
  redis-data:
