parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Redis\PhpRedisClient:
        arguments:
            $host: '%env(REDIS_HOST)%'
            $port: '%env(REDIS_PORT)%'
